###
post http://localhost:3000/players
Content-Type: application/json

 {
    "squadNumber": 32,
    "firstName": "Joel",
    "lastName": "Matip",
    "position": "Defender",
    "nationality": "Cameroon",
    "dateOfBirth": "1991/08/08"
  }

###
get http://localhost:3000/players
Content-Type: application/json

###
put http://localhost:3000/players
Content-Type: application/json

{
  "data": {
    "firstName": "Virgil"
  },
  "where": {
    "id": 2
  }
}

###
delete http://localhost:3000/players
Content-Type: application/json

{
 "id": 5
}
