###
post http://localhost:3000/players
Content-Type: application/json

{
    "squadNumber": 3,
    "firstName": "",
    "lastName": "Fabinho",
    "position": "Midfielder",
    "nationality": "Brazil",
    "dateOfBirth": "1993/10/23"
}

###
get http://localhost:3000/players
Content-Type: application/json

###
put http://localhost:3000/players
Content-Type: application/json

{
  "data": {
    "firstName": "Virgil"
  },
  "where": {
    "id": 2
  }
}

###
delete http://localhost:3000/players
Content-Type: application/json

{
 "id": 5
}
